import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import * as cookieParser from 'cookie-parser';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, {
    cors: true,
    logger: ['log', 'error', 'warn', 'debug', 'verbose'],
  });
  app.use(cookieParser());
  const options = new DocumentBuilder()
    .setTitle('Activise Overview')
    .setDescription(
      'Routes generated by @nestjsx/crud, overview generated by @nestjs/swagger.' +
        ' For Frontend and Backend Devs.',
    )
    .setVersion('1.0')
    .addBearerAuth()
    .build();
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('/api/docs', app, document);
  await app.listen(process.env.PORT || 5000);
}

bootstrap();
